flowchart TB
  classDef module fill:#f9f,stroke:#333,stroke-width:2px,color:#333,font-weight:bold;
  classDef file fill:#D1C4E9,stroke:#666,stroke-width:1px,color:#333;
  classDef doc fill:#D1C4E9,stroke:#666,stroke-width:1px,color:#333;
  classDef focusNode stroke:#007bff,stroke-width:3px;
  linkStyle default stroke:#CCCCCC,stroke-width:1px

  %% -- Nodes and Subgraphs --
  subgraph sg_1B ["1B<br>src"]
    style sg_1B fill:#282828,stroke:#39FF14,stroke-width:4px
  end

  %% -- Fallback Node Definitions --

  %% -- Dependencies --